module.exports = {

  // Main sidebar with everything listed
  docsSidebar: [
  { type: 'doc', id: 'index', label: 'Docs' },
  { type: 'link', label: '🎨 Studio',         href: '/docs/agent-studio/overview' },
  { type: 'link', label: '🔧 Weaver',         href: '/docs/agent-weaver/overview' },
  { type: 'link', label: '🖥️ Runtime',        href: '/docs/agent-runtime/overview' },
  { type: 'link', label: '🚢 Deployments',    href: '/docs/agent-deployments/overview' },
  { type: 'link', label: '🤝 Collaboration',  href: '/docs/agent-collaboration/overview' },
  { type: 'link', label: '📑 Templates',      href: '/docs/agent-templates/overview' },
],

  // only your Introduction pages
  introSidebar: [
    { type: 'link', label: '← Back to Docs', href: '/docs' },
    { type: 'doc',  id: 'introduction/overview', label: '🚀 Introduction' },
    { type: 'autogenerated', dirName: 'introduction' },
  ],

  // only Agent Studio
  agentStudioSidebar: [
    { type: 'link', label: '← Back to Docs', href: '/docs' },
    { type: 'link', label: '🚀 Introduction',         href: '/docs/introduction/overview' },
    { type: 'doc',  id: 'agent-studio/overview', label: '🎨 Agent Studio' },
    { type: 'autogenerated', dirName: 'agent-studio' },
  ],

  // only Agent Weaver
  agentWeaverSidebar: [
    { type: 'link', label: '← Back to Docs', href: '/docs' },
    { type: 'doc',  id: 'agent-weaver/overview', label: '🔧 Agent Weaver' },
    { type: 'autogenerated', dirName: 'agent-weaver' },
  ],

  // only Agent Runtime
  agentRuntimeSidebar: [
    { type: 'link', label: '← Back to Docs', href: '/docs' },
    { type: 'doc',  id: 'agent-runtime/overview', label: '🖥️ Agent Runtime' },
    { type: 'autogenerated', dirName: 'agent-runtime' },
  ],

  // only Agent Deployments
  agentDeploymentsSidebar: [
    { type: 'link', label: '← Back to Docs', href: '/docs' },
    { type: 'doc',  id: 'agent-deployments/overview', label: '🚢 Agent Deployments' },
    { type: 'autogenerated', dirName: 'agent-deployments' },
  ],

  // only Agent Collaboration
  agentCollaborationSidebar: [
    { type: 'link', label: '← Back to Docs', href: '/docs' },
    { type: 'doc',  id: 'agent-collaboration/overview', label: '🤝 Agent Collaboration' },
    { type: 'autogenerated', dirName: 'agent-collaboration' },
  ],

  // only Agent Templates
  agentTemplatesSidebar: [
    { type: 'link', label: '← Back to Docs', href: '/docs' },
    { type: 'doc',  id: 'agent-templates/overview', label: '📑 Agent Templates' },
    { type: 'autogenerated', dirName: 'agent-templates' },
  ],

  // only Features
  featuresSidebar: [
    { type: 'link', label: '← Back to Docs', href: '/docs' },
    { type: 'doc',  id: 'features/overview', label: '✨ Features' },
    { type: 'autogenerated', dirName: 'features' },
  ],

  // only Account
accountSidebar: [
  { type: 'link', label: '← Back to Docs', href: '/docs' },
  { type: 'doc',  id: 'account/overview', label: '👤 Account' },
  { type: 'autogenerated', dirName: 'account' },
],

  // only Account Management
accounManagementSidebar: [
  { type: 'link', label: '← Back to Docs', href: '/docs' },
  { type: 'doc',  id: 'account-management/overview', label: '🛠️ Account Management' },
  { type: 'autogenerated', dirName: 'account-management' },
],

  // only Pricing
pricingSidebar: [
  { type: 'link', label: '← Back to Docs', href: '/docs' },
  { type: 'doc',  id: 'pricing/overview', label: '💰 Pricing' },
  { type: 'autogenerated', dirName: 'pricing' },
],

  // only Tutorials
tutorialsSidebar: [
  { type: 'link', label: '← Back to Docs', href: '/docs' },
  { type: 'doc',  id: 'tutorials/overview', label: '📚 Tutorials' },
  { type: 'autogenerated', dirName: 'tutorials' },
],
};